version: '3.7'
services:
  magento:
    build: .
    ports:
      - "7070:80"
    links:
      - database
    env_file:
      - docker-compose.env
    extra_hosts:
      - magento.local:172.17.0.1
      - freterapido.local:172.17.0.1
    volumes:
      # code
      - ./app/code/community/Freterapido:/var/www/html/app/code/community/Freterapido
      # design
      - ./app/design/frontend/base/default/template/freterapido:/var/www/html/app/design/frontend/base/default/template/freterapido
      - ./app/design/frontend/base/default/layout/freterapido:/var/www/html/app/design/frontend/base/default/layout/freterapido
      # etc
      - ./app/etc/modules/Freterapido_Freterapido.xml:/var/www/html/app/etc/modules/Freterapido_Freterapido.xml
      - ./app/etc/modules/Freterapido_ProductPageShipping.xml:/var/www/html/app/etc/modules/Freterapido_ProductPageShipping.xml
      # skin
      - ./skin/frontend/base/default/css/freterapido:/var/www/html/skin/frontend/base/default/css/freterapido

  database:
    image: mysql:5.6.23
    volumes:
      - magento-data:/var/lib/mysql/data
    env_file:
      - docker-compose.env

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   ports:
  #     - "5051:80"
  #   env_file:
  #     - docker-compose.env
  #   links:
  #     - database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    labels:
    - com.freterapido.project=database
    - com.freterapido.type=dev
    ports:
    - 5051:80
    volumes:
    - ./database/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    environment:
    - PMA_ARBITRARY=1
    - PMA_PORT=3306
    - PMA_HOST=database
    - PMA_USER=magento
    - PMA_PASSWORD=magento

volumes:
  magento-data: